// #include<iostream>
// using namespace std;

// class car{
//     public:
//     int no;
//     int seq;
// };

// int main(){
//     car kia;
//     kia.no = 2730;
//     kia.seq = 1;
//     cout<<kia.no<<endl;
//     cout<<kia.seq;
// }




// #include<iostream>
// using namespace std;

// class calculator{
//     private:
//     int a=4;
    
//     int b=4;

//     public:

//     void sum(){
//         cout<<a+b;
//     }

//     void prod(){
//         cout<<a*b;
//     }
// };


// int main(){
//   calculator sumpro;
//   sumpro.sum();
//   sumpro.prod();

// }


